import { spawn, exec } from "child_process";
import { promisify } from "util";
import { Project, Artifact } from "../drizzle/schema";
import { ADM_PHASES } from "../shared/togafArtifacts";

const execAsync = promisify(exec);

// Cache the manus-mcp-cli path
let mcpCliPath: string | null = null;

/**
 * Find the manus-mcp-cli executable path
 */
async function findMcpCliPath(): Promise<string> {
  if (mcpCliPath) return mcpCliPath;
  
  try {
    const { stdout } = await execAsync('which manus-mcp-cli');
    mcpCliPath = stdout.trim();
    console.log('Found manus-mcp-cli at:', mcpCliPath);
    return mcpCliPath;
  } catch (error) {
    // Fallback to common paths
    const paths = ['/usr/local/bin/manus-mcp-cli', '/usr/bin/manus-mcp-cli', 'manus-mcp-cli'];
    for (const path of paths) {
      try {
        await execAsync(`test -x ${path}`);
        mcpCliPath = path;
        console.log('Found manus-mcp-cli at:', mcpCliPath);
        return mcpCliPath;
      } catch {}
    }
    throw new Error('manus-mcp-cli not found in PATH');
  }
}

/**
 * Execute MCP command for Notion using spawn to avoid shell escaping issues
 */
async function executeMCP(toolName: string, input: any): Promise<any> {
  const inputJson = JSON.stringify(input);
  const cliPath = await findMcpCliPath();
  
  return new Promise((resolve, reject) => {
    const args = ['tool', 'call', toolName, '--server', 'notion', '--input', inputJson];
    
    console.log('Executing MCP command:', cliPath, args.slice(0, 5).join(' '));
    
    const child = spawn(cliPath, args, {
      env: { ...process.env, PATH: `${process.env.PATH}:/usr/local/bin:/usr/bin:/bin` }
    });
    
    let stdout = '';
    let stderr = '';
    
    child.stdout.on('data', (data) => {
      stdout += data.toString();
    });
    
    child.stderr.on('data', (data) => {
      stderr += data.toString();
    });
    
    child.on('close', (code) => {
      if (code !== 0) {
        console.error('Notion MCP error:', stderr);
        reject(new Error(`Notion integration failed: ${stderr}`));
        return;
      }
      
      console.log('Notion MCP stdout:', stdout.substring(0, 500));
      
      // Parse the result from stdout
      const lines = stdout.split('\n');
      const resultLine = lines.find(line => line.includes('Result:'));
      if (resultLine) {
        const jsonStart = resultLine.indexOf('{');
        if (jsonStart !== -1) {
          try {
            resolve(JSON.parse(resultLine.substring(jsonStart)));
            return;
          } catch (e) {
            console.error('Failed to parse result:', e);
          }
        }
      }
      
      resolve({ success: true, output: stdout });
    });
    
    child.on('error', (error) => {
      console.error('Notion MCP spawn error:', error);
      reject(new Error(`Failed to spawn manus-mcp-cli: ${error.message}`));
    });
  });
}

/**
 * Create a Notion page for a TOGAF project
 */
export async function createProjectInNotion(project: Project): Promise<string> {
  // Create main project page
  const projectPage = await executeMCP('notion-create-pages', {
    pages: [{
      properties: {
        title: `[TOGAF] ${project.name}`
      },
      content: `# ${project.name}

## Project Overview
${project.description || 'No description provided'}

**Current Phase:** ${project.currentPhase}
**Status:** ${project.status}
**Created:** ${new Date(project.createdAt).toLocaleDateString()}

---

## ADM Phases

This project follows the TOGAF Architecture Development Method (ADM). Each phase below contains the artifacts created during that phase.

${ADM_PHASES.map(phase => `### ${phase}\n\nArtifacts will be organized under this phase.\n`).join('\n')}`
    }]
  });

  return projectPage.url || projectPage.id;
}

/**
 * Create a Notion page for an artifact
 */
export async function createArtifactInNotion(
  artifact: Artifact,
  projectNotionUrl: string,
  content?: string
): Promise<string> {
  // First, fetch the project page to get its ID
  const projectPage = await executeMCP('notion-fetch', {
    id: projectNotionUrl
  });

  const artifactContent = content || artifact.content || artifact.content || 'No content generated yet.';

  // Create artifact page as a child of the project page
  const artifactPage = await executeMCP('notion-create-pages', {
    parent: {
      page_id: projectPage.id
    },
    pages: [{
      properties: {
        title: `${artifact.phase} - ${artifact.name}`
      },
      content: `# ${artifact.name}

**Type:** ${artifact.type}
**Phase:** ${artifact.phase}
**Status:** ${artifact.status}
**Created:** ${new Date(artifact.createdAt).toLocaleDateString()}

---

## Content

${artifactContent}

---

*Generated by TOGAF Artifact Generator*`
    }]
  });

  return artifactPage.url || artifactPage.id;
}

/**
 * Update an existing Notion page with new content
 */
export async function updateArtifactInNotion(
  notionUrl: string,
  artifact: Artifact,
  content?: string
): Promise<void> {
  const artifactContent = content || artifact.content || artifact.content || 'No content generated yet.';

  await executeMCP('notion-update-page', {
    id: notionUrl,
    content: `# ${artifact.name}

**Type:** ${artifact.type}
**Phase:** ${artifact.phase}
**Status:** ${artifact.status}
**Updated:** ${new Date(artifact.updatedAt).toLocaleDateString()}

---

## Content

${artifactContent}

---

*Generated by TOGAF Artifact Generator*`
  });
}

/**
 * Create a structured database in Notion for TOGAF artifacts
 */
export async function createTOGAFDatabaseInNotion(projectName: string): Promise<string> {
  const database = await executeMCP('notion-create-database', {
    title: `${projectName} - TOGAF Artifacts`,
    properties: {
      "Artifact Name": {
        type: "title"
      },
      "Type": {
        type: "select",
        options: [
          { name: "catalog", color: "blue" },
          { name: "matrix", color: "green" },
          { name: "diagram", color: "purple" }
        ]
      },
      "Phase": {
        type: "select",
        options: ADM_PHASES.map((phase, idx) => ({
          name: phase,
          color: ["gray", "brown", "orange", "yellow", "green", "blue", "purple", "pink", "red"][idx % 9]
        }))
      },
      "Status": {
        type: "select",
        options: [
          { name: "not_started", color: "gray" },
          { name: "in_progress", color: "yellow" },
          { name: "completed", color: "green" },
          { name: "reviewed", color: "blue" }
        ]
      },
      "Created Date": {
        type: "date"
      },
      "Updated Date": {
        type: "date"
      }
    }
  });

  return database.url || database.id;
}

/**
 * Add artifact to Notion database
 */
export async function addArtifactToDatabase(
  databaseUrl: string,
  artifact: Artifact
): Promise<string> {
  // First fetch the database to get the data source ID
  const database = await executeMCP('notion-fetch', {
    id: databaseUrl
  });

  const dataSourceId = database.data_sources?.[0]?.id;
  if (!dataSourceId) {
    throw new Error('Could not find data source ID for database');
  }

  const page = await executeMCP('notion-create-pages', {
    parent: {
      data_source_id: dataSourceId
    },
    pages: [{
      properties: {
        "Artifact Name": artifact.name,
        "Type": artifact.type,
        "Phase": artifact.phase,
        "Status": artifact.status,
        "date:Created Date:start": artifact.createdAt.toISOString().split('T')[0],
        "date:Created Date:is_datetime": 0,
        "date:Updated Date:start": artifact.updatedAt.toISOString().split('T')[0],
        "date:Updated Date:is_datetime": 0
      },
      content: artifact.content || artifact.content || 'No content yet.'
    }]
  });

  return page.url || page.id;
}

/**
 * Search for existing project in Notion
 */
export async function searchProjectInNotion(projectName: string): Promise<any> {
  const result = await executeMCP('notion-search', {
    query: `[TOGAF] ${projectName}`,
    query_type: 'internal'
  });

  return result.results?.[0];
}
