import { exec } from "child_process";
import { promisify } from "util";
import { Project, Artifact } from "../drizzle/schema";
import { ADM_PHASES } from "../shared/togafArtifacts";

const execAsync = promisify(exec);

/**
 * Execute MCP command for Notion
 */
async function executeMCP(toolName: string, input: any): Promise<any> {
  const inputJson = JSON.stringify(input).replace(/"/g, '\\"');
  const command = `manus-mcp-cli tool call ${toolName} --server notion --input "${inputJson}"`;
  
  try {
    const { stdout, stderr } = await execAsync(command);
    if (stderr && !stderr.includes('Tool call completed')) {
      console.error('Notion MCP stderr:', stderr);
    }
    
    // Parse the result from stdout
    const lines = stdout.split('\n');
    const resultLine = lines.find(line => line.includes('Result:'));
    if (resultLine) {
      const jsonStart = resultLine.indexOf('{');
      if (jsonStart !== -1) {
        return JSON.parse(resultLine.substring(jsonStart));
      }
    }
    
    return { success: true, output: stdout };
  } catch (error: any) {
    console.error('Notion MCP error:', error);
    throw new Error(`Notion integration failed: ${error.message}`);
  }
}

/**
 * Create a Notion page for a TOGAF project
 */
export async function createProjectInNotion(project: Project): Promise<string> {
  // Create main project page
  const projectPage = await executeMCP('notion-create-pages', {
    pages: [{
      properties: {
        title: `[TOGAF] ${project.name}`
      },
      content: `# ${project.name}

## Project Overview
${project.description || 'No description provided'}

**Current Phase:** ${project.currentPhase}
**Status:** ${project.status}
**Created:** ${new Date(project.createdAt).toLocaleDateString()}

---

## ADM Phases

This project follows the TOGAF Architecture Development Method (ADM). Each phase below contains the artifacts created during that phase.

${ADM_PHASES.map(phase => `### ${phase}\n\nArtifacts will be organized under this phase.\n`).join('\n')}`
    }]
  });

  return projectPage.url || projectPage.id;
}

/**
 * Create a Notion page for an artifact
 */
export async function createArtifactInNotion(
  artifact: Artifact,
  projectNotionUrl: string,
  content?: string
): Promise<string> {
  // First, fetch the project page to get its ID
  const projectPage = await executeMCP('notion-fetch', {
    id: projectNotionUrl
  });

  const artifactContent = content || artifact.generatedContent || artifact.content || 'No content generated yet.';

  // Create artifact page as a child of the project page
  const artifactPage = await executeMCP('notion-create-pages', {
    parent: {
      page_id: projectPage.id
    },
    pages: [{
      properties: {
        title: `${artifact.phase} - ${artifact.name}`
      },
      content: `# ${artifact.name}

**Type:** ${artifact.type}
**Phase:** ${artifact.phase}
**Status:** ${artifact.status}
**Created:** ${new Date(artifact.createdAt).toLocaleDateString()}

---

## Content

${artifactContent}

---

*Generated by TOGAF Artifact Generator*`
    }]
  });

  return artifactPage.url || artifactPage.id;
}

/**
 * Update an existing Notion page with new content
 */
export async function updateArtifactInNotion(
  notionUrl: string,
  artifact: Artifact,
  content?: string
): Promise<void> {
  const artifactContent = content || artifact.generatedContent || artifact.content || 'No content generated yet.';

  await executeMCP('notion-update-page', {
    id: notionUrl,
    content: `# ${artifact.name}

**Type:** ${artifact.type}
**Phase:** ${artifact.phase}
**Status:** ${artifact.status}
**Updated:** ${new Date(artifact.updatedAt).toLocaleDateString()}

---

## Content

${artifactContent}

---

*Generated by TOGAF Artifact Generator*`
  });
}

/**
 * Create a structured database in Notion for TOGAF artifacts
 */
export async function createTOGAFDatabaseInNotion(projectName: string): Promise<string> {
  const database = await executeMCP('notion-create-database', {
    title: `${projectName} - TOGAF Artifacts`,
    properties: {
      "Artifact Name": {
        type: "title"
      },
      "Type": {
        type: "select",
        options: [
          { name: "catalog", color: "blue" },
          { name: "matrix", color: "green" },
          { name: "diagram", color: "purple" }
        ]
      },
      "Phase": {
        type: "select",
        options: ADM_PHASES.map((phase, idx) => ({
          name: phase,
          color: ["gray", "brown", "orange", "yellow", "green", "blue", "purple", "pink", "red"][idx % 9]
        }))
      },
      "Status": {
        type: "select",
        options: [
          { name: "not_started", color: "gray" },
          { name: "in_progress", color: "yellow" },
          { name: "completed", color: "green" },
          { name: "reviewed", color: "blue" }
        ]
      },
      "Created Date": {
        type: "date"
      },
      "Updated Date": {
        type: "date"
      }
    }
  });

  return database.url || database.id;
}

/**
 * Add artifact to Notion database
 */
export async function addArtifactToDatabase(
  databaseUrl: string,
  artifact: Artifact
): Promise<string> {
  // First fetch the database to get the data source ID
  const database = await executeMCP('notion-fetch', {
    id: databaseUrl
  });

  const dataSourceId = database.data_sources?.[0]?.id;
  if (!dataSourceId) {
    throw new Error('Could not find data source ID for database');
  }

  const page = await executeMCP('notion-create-pages', {
    parent: {
      data_source_id: dataSourceId
    },
    pages: [{
      properties: {
        "Artifact Name": artifact.name,
        "Type": artifact.type,
        "Phase": artifact.phase,
        "Status": artifact.status,
        "date:Created Date:start": artifact.createdAt.toISOString().split('T')[0],
        "date:Created Date:is_datetime": 0,
        "date:Updated Date:start": artifact.updatedAt.toISOString().split('T')[0],
        "date:Updated Date:is_datetime": 0
      },
      content: artifact.generatedContent || artifact.content || 'No content yet.'
    }]
  });

  return page.url || page.id;
}

/**
 * Search for existing project in Notion
 */
export async function searchProjectInNotion(projectName: string): Promise<any> {
  const result = await executeMCP('notion-search', {
    query: `[TOGAF] ${projectName}`,
    query_type: 'internal'
  });

  return result.results?.[0];
}
